### ISSUE TITLE
Split view footer not pinning to bottom of screen

### ISSUE THREAD

**Issue by abhishekmaheshwari1106** [blackbaud/skyux-split-view#26]
### Expected behavior

1. When using `sky-split-view` with `sky-split-view-workspace-footer`, the footer should be pinned to the bottom of the screen such that it should be always visible.
2. When the content of either side of the split view panel increases the viewport, then a scrollbar should be added to that particular side rather than adding a scroll on the whole page.
3. The width of panels should be defined In percentage rather than pixel as to maintain a responsive UI,

### Actual behavior
1. The footer is not pinned to the bottom of the screen rather it slides to the bottom of the page. If the content on the left or right side of the split view is more than the currently visible screen then footer slides to the bottom of the page.  
2. When using the split view panel each section should be able to add a scroll to its respective container rather than adding a scroll on the complete page.
3. The width of panels should be defined In percentage rather than pixel as to maintain a responsive UI

AB#1564785

**Comment by Blackbaud-TrevorBurch** [comment]
In `4.1.0`
